# Change baseurl before deploy
baseurl = "https://blog.juilpark.com/"
locale  = "ko-kr"
title   = "한서연의 연구노트"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "ko"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Pagination settings
[pagination]
    pagerSize = 10

# Image cache (for Cloudflare Workers build environment)
[caches]
    [caches.images]
        dir = ':cacheDir/images'
